"""Provider-neutral cognitive domain for the five-ASI marketing brain.

This package intentionally owns only semantic cognition contracts. It must not
import runtime, tools, provider integrations, persistence, or connector code.
"""

from brain.contracts import (
    ActionIntent,
    BrainAgentId,
    DecisionDisposition,
    DecisionRecord,
    EvidenceNeed,
    GoalSpec,
    GoalStatus,
    StopDecision,
    StopReason,
    UnknownRecord,
)
from brain.hypotheses import (
    HypothesisAssessment,
    HypothesisCandidate,
    HypothesisPortfolioDecision,
    HypothesisPortfolioRequest,
    InformationValue,
    InquiryCost,
    ProbePrediction,
    ResearchAgenda,
    ResearchAgendaRequest,
    ResearchProbe,
    ResearchRecommendation,
    assess_hypothesis_portfolio,
    prioritize_research_agenda,
)
from brain.learning import (
    LearningClaimKind,
    LearningDecision,
    LearningDisposition,
    LearningEpisode,
    LearningMethod,
    analyze_learning_episode,
)
from brain.meta_learning import (
    MetaLearningDecision,
    MetaLearningDisposition,
    MetaLearningRequest,
    StrategyPerformance,
    StrategyTrial,
    TrialEffect,
    evaluate_meta_learning,
)
from brain.metacognition import (
    GapResolutionDirective,
    KnowledgeGap,
    KnowledgeGapKind,
    KnowledgeState,
    LearningStrategy,
    MetacognitionDecision,
    MetacognitionRequest,
    assess_metacognition,
    derive_knowledge_gaps,
)
from brain.planning import (
    PlanRevision,
    PlanSnapshot,
    PlanStatus,
    PlanStep,
    PlanStepState,
    RevisionTrigger,
    apply_plan_revision,
    ready_step_ids,
)
from brain.reasoning import (
    ReasoningAssessment,
    ReasoningDecision,
    ReasoningDepth,
    Reversibility,
    SignalLevel,
    select_reasoning_depth,
)

__all__ = [
    "ActionIntent",
    "BrainAgentId",
    "DecisionDisposition",
    "DecisionRecord",
    "EvidenceNeed",
    "GapResolutionDirective",
    "GoalSpec",
    "GoalStatus",
    "HypothesisAssessment",
    "HypothesisCandidate",
    "HypothesisPortfolioDecision",
    "HypothesisPortfolioRequest",
    "InformationValue",
    "InquiryCost",
    "KnowledgeGap",
    "KnowledgeGapKind",
    "KnowledgeState",
    "LearningClaimKind",
    "LearningDecision",
    "LearningDisposition",
    "LearningEpisode",
    "LearningMethod",
    "LearningStrategy",
    "MetaLearningDecision",
    "MetaLearningDisposition",
    "MetaLearningRequest",
    "MetacognitionDecision",
    "MetacognitionRequest",
    "PlanRevision",
    "PlanSnapshot",
    "PlanStatus",
    "PlanStep",
    "PlanStepState",
    "ProbePrediction",
    "ReasoningAssessment",
    "ReasoningDecision",
    "ReasoningDepth",
    "ResearchAgenda",
    "ResearchAgendaRequest",
    "ResearchProbe",
    "ResearchRecommendation",
    "Reversibility",
    "RevisionTrigger",
    "SignalLevel",
    "StopDecision",
    "StopReason",
    "StrategyPerformance",
    "StrategyTrial",
    "TrialEffect",
    "UnknownRecord",
    "analyze_learning_episode",
    "apply_plan_revision",
    "assess_hypothesis_portfolio",
    "assess_metacognition",
    "derive_knowledge_gaps",
    "evaluate_meta_learning",
    "prioritize_research_agenda",
    "ready_step_ids",
    "select_reasoning_depth",
]
