from pathlib import Path

path = Path("runtime/engine.py")
text = path.read_text(encoding="utf-8")

intel_anchor = '''        is_research_mode = bool(emitter and emitter.mode == ProgressMode.RESEARCH_INQUIRY.value)\n        if emitter and not is_research_mode:\n'''
intel_replacement = '''        is_research_mode = bool(emitter and emitter.mode == ProgressMode.RESEARCH_INQUIRY.value)\n        if context.status == RuntimeStatus.FAILED or context.stage_outputs.get("cmo_initial", {}).get("status") == "FAILED":\n            context.status = RuntimeStatus.FAILED\n            if emitter:\n                emitter.emit(\n                    ProgressEventType.RUN_FAILED,\n                    stage="INTELLIGENCE",\n                    agent="INTELLIGENCE",\n                    message="Giai đoạn Intelligence thất bại do giai đoạn trước gặp sự cố",\n                    metadata={"error": "PREVIOUS_STAGE_FAILED"},\n                )\n            output = {\n                "stage": "INTELLIGENCE",\n                "agent": "intelligence",\n                "status": "FAILED",\n                "error": "PREVIOUS_STAGE_FAILED",\n                "market_findings": "",\n                "search_receipt_id": None,\n                "citations": [],\n            }\n            context.stage_outputs["intelligence"] = output\n            context.create_checkpoint()\n            return output\n        if emitter and not is_research_mode:\n'''
assert text.count(intel_anchor) == 1, f"intelligence insertion anchor count={text.count(intel_anchor)}"
text = text.replace(intel_anchor, intel_replacement, 1)

intel_late = '''        if context.status == RuntimeStatus.FAILED or context.stage_outputs.get("cmo_initial", {}).get("status") == "FAILED":\n            context.status = RuntimeStatus.FAILED\n            if emitter:\n                emitter.emit(\n                    ProgressEventType.RUN_FAILED,\n                    stage="INTELLIGENCE",\n                    agent="INTELLIGENCE",\n                    message="Giai đoạn Intelligence thất bại do giai đoạn trước gặp sự cố",\n                    metadata={"error": "PREVIOUS_STAGE_FAILED"},\n                )\n            output = {\n                "stage": "INTELLIGENCE",\n                "agent": "intelligence",\n                "status": "FAILED",\n                "error": "PREVIOUS_STAGE_FAILED",\n                "market_findings": "",\n                "search_receipt_id": search_receipt.execution_id,\n                "citations": [c.citation_id for c in k_res.citations],\n            }\n            context.stage_outputs["intelligence"] = output\n            context.create_checkpoint()\n            return output\n\n'''
assert text.count(intel_late) == 1, f"intelligence late gate count={text.count(intel_late)}"
text = text.replace(intel_late, "", 1)

perf_anchor = '''    def execute_stage_performance(self, context: RuntimeContext) -> Dict[str, Any]:\n        """Stage 5: Performance Analytics, Attribution & Experiment Portfolio."""\n        context.current_stage = RuntimeStage.PERFORMANCE\n        emitter = self._get_emitter(context)\n        if emitter:\n'''
perf_replacement = '''    def execute_stage_performance(self, context: RuntimeContext) -> Dict[str, Any]:\n        """Stage 5: Performance Analytics, Attribution & Experiment Portfolio."""\n        context.current_stage = RuntimeStage.PERFORMANCE\n        emitter = self._get_emitter(context)\n        if context.status == RuntimeStatus.FAILED or context.stage_outputs.get("creative", {}).get("status") == "FAILED":\n            context.status = RuntimeStatus.FAILED\n            if emitter:\n                emitter.emit(\n                    ProgressEventType.RUN_FAILED,\n                    stage="PERFORMANCE",\n                    agent="PERFORMANCE",\n                    message="Giai đoạn Performance thất bại do giai đoạn trước gặp sự cố",\n                    metadata={"error": "PREVIOUS_STAGE_FAILED"},\n                )\n            output = {\n                "stage": "PERFORMANCE",\n                "agent": "performance",\n                "status": "FAILED",\n                "error": "PREVIOUS_STAGE_FAILED",\n                "funnel_kpi": "",\n                "experiment_blueprint": {},\n                "analytics_receipt_id": None,\n                "analytics_data_status": "NOT_ATTEMPTED:PREVIOUS_STAGE_FAILED",\n                "calc_receipt_id": None,\n                "citations": [],\n            }\n            context.stage_outputs["performance"] = output\n            context.create_checkpoint()\n            return output\n        if emitter:\n'''
assert text.count(perf_anchor) == 1, f"performance insertion anchor count={text.count(perf_anchor)}"
text = text.replace(perf_anchor, perf_replacement, 1)

perf_late = '''        if context.status == RuntimeStatus.FAILED or context.stage_outputs.get("creative", {}).get("status") == "FAILED":\n            context.status = RuntimeStatus.FAILED\n            if emitter:\n                emitter.emit(\n                    ProgressEventType.RUN_FAILED,\n                    stage="PERFORMANCE",\n                    agent="PERFORMANCE",\n                    message="Giai đoạn Performance thất bại do giai đoạn trước gặp sự cố",\n                    metadata={"error": "PREVIOUS_STAGE_FAILED"},\n                )\n            output = {\n                "stage": "PERFORMANCE",\n                "agent": "performance",\n                "status": "FAILED",\n                "error": "PREVIOUS_STAGE_FAILED",\n                "funnel_kpi": "",\n                "experiment_blueprint": {},\n                "analytics_receipt_id": analytics_receipt.execution_id,\n                "analytics_data_status": telemetry_status,\n                "calc_receipt_id": None,\n                "citations": [c.citation_id for c in k_res.citations],\n            }\n            context.stage_outputs["performance"] = output\n            context.create_checkpoint()\n            return output\n\n'''
assert text.count(perf_late) == 1, f"performance late gate count={text.count(perf_late)}"
text = text.replace(perf_late, "", 1)

path.write_text(text, encoding="utf-8")
